language: node_js

node_js:
  - node

before_script:
  - npm install -g codeclimate-test-reporter

script:
  - npm test

after_success:
  - CODE_CLIMATE_REPO_TOKEN=$CODE_CLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info